export const ERROR_CODES = {
  INVALID_INPUT: "INVALID_INPUT",
  NOT_A_CHANNEL_URL: "NOT_A_CHANNEL_URL",
  CHANNEL_NOT_FOUND: "CHANNEL_NOT_FOUND",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  API_FORBIDDEN: "API_FORBIDDEN",
  API_ERROR: "API_ERROR",
  SCRAPE_FETCH_FAILED: "SCRAPE_FETCH_FAILED",
  SCRAPE_CONSENT_WALL: "SCRAPE_CONSENT_WALL",
  SCRAPE_PARSE_FAILED: "SCRAPE_PARSE_FAILED",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RATE_LIMITED: "RATE_LIMITED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export const DEFAULTS = {
  CACHE_TTL_SECONDS: 300,
  RATE_LIMIT_PER_MINUTE: 30,
  MAX_HANDLE_LENGTH: 200,
  RATE_LIMIT_CLEANUP_MINUTES: 60,
  VIDEO_MAX_RESULTS: 12,
} as const;
